# Generated by Django 4.0.3 on 2022-03-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
